# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('markerName', models.CharField(default=None, max_length=1250, null=True)),
                ('marker_type', models.CharField(default=None, max_length=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
            ],
        ),
    ]
