# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='retweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
