# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='retweets',
            new_name='retweet',
        ),
    ]
